
version: '3.4'
services:

  jd_scripts:
    image: pkpkgtr/jd_scripts:latest
    network_mode: host
    # 配置服务器资源约束。此例子中服务被限制为使用内存不超过200M以及cpu不超过0.2（单核的20%）
    # 经过实际测试，建议不低于200M
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: 200M
    container_name: jd_scripts1
    restart: always
    volumes:
      - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
      - ./logs:/scripts/logs
    tty: true
    # 因为更换仓库地址可能git pull的dns解析不到，可以在配置追加hosts
    extra_hosts:
      - "gitee.com:180.97.125.228"
      - "github.com:13.229.188.59"
      - "raw.githubusercontent.com:151.101.228.133"
    environment:
      #脚本更新仓库地址，配置了会切换到对应的地址
      - REPO_URL=git@github.com:pkpkgtr1/jd_scripts.git
      # 注意环境变量填写值的时候一律不需要引号（""或者''）下面这些只是事例，根据自己的需求增加删除
      #jd cookies
      # 例: JD_COOKIE=
      - JD_COOKIE=
      #微信server酱通
      - PUSH_KEY=
      #Bark App通知
      - BARK_PUSH=
      #telegram机器人通知
      - TG_BOT_TOKEN=
      - TG_USER_ID=
      #钉钉机器人通知
      - DD_BOT_TOKEN=
      - DD_BOT_SECRET=
      #企业微信机器人通知
      - QYWX_KEY=
      #京东种豆得豆
      - PLANT_BEAN_SHARECODES=
      #京东农场
      # 例: FRUITSHARECODES=京东农场的互助码
      - FRUITSHARECODES=
      #京东萌宠
      # 例: PETSHARECODES=东东萌宠的互助码
      - PETSHARECODES=
      # 宠汪汪的喂食数量
      - JOY_FEED_COUNT=
      #惊喜工厂
      - DREAM_FACTORY_SHARE_CODES=IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==&IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==&IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==&IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==&IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==&IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==&IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==&IeLLA2B976ZNGz0-tZOz9g==@ydNl406Z0DsdM7DI8XGH1Q==@goj6M8YzWy0sQVHcES6mLg==@9_63bss-4jmSHGygXAC3Rw==@vK4-VvzGZk9-bJeX77eJrA==@57nF3Lgd0glKhRScYO-GRQ==@_HNzd6NETxzlOevqSv7MZQ==@4AoI9wl3FtLoCmM5CCJZ-g==@gPCxjoY_bYW9uDSX8IKGbA==@AWQb4J4sm-JxL0c7TQUdXQ==@-RfuUpz0XCWEFhjwNg6eiA==@A2l2tj4Az-SgmVG7meLRjb5r30e8PaOshXo1ErMQ7yg=@PWBKU3owVYtKcms62KxIWg==
      #东东超市
      # - SUPERMARKET_SHARECODES=
      #兑换多少数量的京豆（20，或者1000京豆,或者其他奖品的文字）
      # 例: MARKET_COIN_TO_BEANS=1000
      - MARKET_COIN_TO_BEANS=
      #是否开启debug模式打印日志
      # 例: JD_DEBUG=false
      - JD_DEBUG=
      #使用自定义定任务追加默认任务之后，上面volumes挂载之后这里配置对应的文件名，和自定义文件使用方式为overwrite
      - CUSTOM_LIST_FILE=my_crontab_list.sh

